import { User } from './types';

export const CORE_BANKING_USERS = [
  { code: 'CBU-001', name: 'Abiodun Adebayo' },
  { code: 'CBU-002', name: 'Chidi Nwosu' },
  { code: 'CBU-003', name: 'Fatimah Bello' },
  { code: 'CBU-004', name: 'Ibrahim Musa' },
  { code: 'CBU-005', name: 'Olumide Johnson' },
  { code: 'CBU-006', name: 'Ngozi Okonkwo' },
  { code: 'CBU-007', name: 'Yetunde Alabi' },
  { code: 'CBU-008', name: 'Babatunde Sogbola' },
  { code: 'CBU-009', name: 'Chinonso Greg' }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alex Morgan',
    email: 'alex.m@nolt.finance',
    role: 'Super Admin',
    status: 'Active',
    referralCode: 'ALEX-ADMIN',
    lastActive: '2 mins ago',
    avatar: 'https://picsum.photos/seed/admin/100/100',
    wrapUser: 'CBU-001 - Abiodun Adebayo',
    hasStaffLoanAccess: true,
    staffLoanMaxCap: 5000000,
    staffLoanAccessGrantedBy: 'HRIS System Auto-Sync',
    staffLoanAccessUpdatedAt: '2025-06-01',
    hrisSyncStatus: 'Synced',
    staffCode: 'NT-101',
    staffDepartment: 'Executive Management',
    staffBadgeTier: 'Gold',
    approvedLoansCount: 42,
    investmentsBookedCount: 12
  },
  {
    id: 'u2',
    name: 'Tunde Bakare',
    email: 't.bakare@nolt.finance',
    role: 'Credit Manager',
    status: 'Active',
    referralCode: 'CRED-T01',
    lastActive: '1 hour ago',
    avatar: 'https://picsum.photos/seed/tunde/100/100',
    wrapUser: 'CBU-002 - Chidi Nwosu',
    hasStaffLoanAccess: true,
    staffLoanMaxCap: 5000000,
    staffLoanAccessGrantedBy: 'Blessing Udoh (HR Officer)',
    staffLoanAccessUpdatedAt: '2025-06-15',
    hrisSyncStatus: 'Synced',
    staffCode: 'NT-108',
    staffDepartment: 'Credit Risk & Analysis',
    staffBadgeTier: 'Silver',
    approvedLoansCount: 31,
    investmentsBookedCount: 7
  },
  {
    id: 'u_o1',
    name: 'Bisi Adekunle',
    email: 'b.ade@nolt.finance',
    role: 'Credit Officer',
    status: 'Active',
    referralCode: 'CRED-B02',
    lastActive: '3 hours ago',
    avatar: 'https://picsum.photos/seed/bisi/100/100',
    wrapUser: 'CBU-003 - Fatimah Bello',
    hasStaffLoanAccess: true,
    staffLoanMaxCap: 3500000,
    staffLoanAccessGrantedBy: 'Funke Akindele (HR Manager)',
    staffLoanAccessUpdatedAt: '2025-06-20',
    hrisSyncStatus: 'Synced',
    staffCode: 'NT-114',
    staffDepartment: 'Credit Risk',
    staffBadgeTier: 'Bronze',
    approvedLoansCount: 18,
    investmentsBookedCount: 4
  },
  {
    id: 'u3',
    name: 'Michael Scott',
    email: 'scott@nolt.finance',
    role: 'Sales Team Lead',
    status: 'Active',
    referralCode: 'SALE-S99',
    lastActive: 'Yesterday',
    avatar: 'https://picsum.photos/seed/scott/100/100',
    wrapUser: 'CBU-004 - Ibrahim Musa',
    hasStaffLoanAccess: true,
    staffLoanMaxCap: 5000000,
    staffLoanAccessGrantedBy: 'Blessing Udoh (HR Officer)',
    staffLoanAccessUpdatedAt: '2025-06-10',
    hrisSyncStatus: 'Synced',
    staffCode: 'NT-112',
    staffDepartment: 'Sales & Business Growth',
    staffBadgeTier: 'Gold',
    approvedLoansCount: 56,
    investmentsBookedCount: 15
  },
  {
    id: 'u4',
    name: 'Jessica Wu',
    email: 'j.wu@nolt.finance',
    role: 'Customer Experience',
    status: 'Pending',
    referralCode: 'CX-JESS',
    lastActive: 'Never',
    avatar: 'https://picsum.photos/seed/jess/100/100',
    hasStaffLoanAccess: false,
    staffLoanMaxCap: 0,
    staffLoanAccessGrantedBy: 'Pending HR Confirmation',
    staffLoanAccessUpdatedAt: '2025-06-25',
    hrisSyncStatus: 'Pending HRIS',
    staffCode: 'NT-120',
    staffDepartment: 'Customer Experience',
    staffBadgeTier: 'Bronze',
    approvedLoansCount: 2,
    investmentsBookedCount: 1
  },
  {
    id: 'u_hr1',
    name: 'Blessing Udoh',
    email: 'b.udoh@nolt.finance',
    role: 'HR Officer',
    status: 'Active',
    referralCode: 'HR-O01',
    lastActive: '5 mins ago',
    avatar: 'https://picsum.photos/seed/blessing/100/100',
    wrapUser: 'CBU-006 - Ngozi Okonkwo',
    hasStaffLoanAccess: true,
    staffLoanMaxCap: 5000000,
    staffLoanAccessGrantedBy: 'Funke Akindele (HR Manager)',
    staffLoanAccessUpdatedAt: '2025-05-01',
    hrisSyncStatus: 'Synced',
    staffCode: 'NT-119',
    staffDepartment: 'Human Resources',
    staffBadgeTier: 'Silver',
    approvedLoansCount: 15,
    investmentsBookedCount: 6
  },
  {
    id: 'u_hr2',
    name: 'Funke Akindele',
    email: 'f.akindele@nolt.finance',
    role: 'HR Manager',
    status: 'Active',
    referralCode: 'HR-M01',
    lastActive: '12 mins ago',
    avatar: 'https://picsum.photos/seed/funke/100/100',
    wrapUser: 'CBU-007 - Yetunde Alabi',
    hasStaffLoanAccess: true,
    staffLoanMaxCap: 5000000,
    staffLoanAccessGrantedBy: 'Super Admin',
    staffLoanAccessUpdatedAt: '2025-05-01',
    hrisSyncStatus: 'Synced',
    staffCode: 'NT-105',
    staffDepartment: 'Human Resources',
    staffBadgeTier: 'Gold',
    approvedLoansCount: 28,
    investmentsBookedCount: 9
  },
  {
    id: 'u5',
    name: 'Chidi Okoro',
    email: 'c.okoro@nolt.finance',
    role: 'Sales Officer',
    status: 'Active',
    referralCode: 'SO-CHIDI',
    lastActive: '10 mins ago',
    avatar: 'https://picsum.photos/seed/chidi/100/100',
    teamLeadId: 'u3',
    wrapUser: 'CBU-005 - Olumide Johnson',
    hasStaffLoanAccess: true,
    staffLoanMaxCap: 2500000,
    staffLoanAccessGrantedBy: 'Blessing Udoh (HR Officer)',
    staffLoanAccessUpdatedAt: '2025-06-18',
    hrisSyncStatus: 'Synced',
    staffCode: 'NT-127',
    staffDepartment: 'Information Technology',
    staffBadgeTier: 'Bronze',
    approvedLoansCount: 20,
    investmentsBookedCount: 3
  },
  {
    id: 'u_agt1',
    name: 'Tunde Davies',
    email: 'tunde.davies@apexbrokerage.ng',
    role: 'Agent',
    status: 'Active',
    referralCode: 'AGT-TUNDE',
    agentCode: 'AGT-702',
    agentReferralUrl: 'https://nolt.finance/invest?ref=AGT-TUNDE',
    agentTier: 'Premier Certified Agent',
    agentTotalCommissionEarned: 350000,
    agentPendingCommission: 55500,
    agentReferredInvestmentsCount: 14,
    lastActive: '5 mins ago',
    avatar: 'https://picsum.photos/seed/agenttunde/100/100',
    wrapUser: 'CBU-008 - Babatunde Sogbola'
  },
  {
    id: 'u_agt2',
    name: 'Amina Bello',
    email: 'amina.bello@wealthbridge.ng',
    role: 'Agent',
    status: 'Active',
    referralCode: 'AGT-AMINA',
    agentCode: 'AGT-804',
    agentReferralUrl: 'https://nolt.finance/invest?ref=AGT-AMINA',
    agentTier: 'Senior Broker Partner',
    agentTotalCommissionEarned: 520000,
    agentPendingCommission: 76500,
    agentReferredInvestmentsCount: 22,
    lastActive: '12 mins ago',
    avatar: 'https://picsum.photos/seed/agentamina/100/100',
    wrapUser: 'CBU-003 - Fatimah Bello'
  }
];
